In [1]:
import numpy as np

In [2]:
ls = [1,2,3,4,5]

In [3]:
# convetting a lsit to array
np.array(ls)

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array(ls)

In [5]:
# ndarray - n dimensional array

type(arr) 

numpy.ndarray

In [6]:
# to create ndimensional array, length of lists must be same

np.array([[1,2,3,4], [5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])

In [8]:
arr.ndim # return the dimensions of an array

1

In [9]:
arr1.ndim

2

In [10]:
# plot an ndarray

np.matrix(ls)


matrix([[1, 2, 3, 4, 5]])

In [11]:
np.asanyarray(ls)  # will convert any item to an array

array([1, 2, 3, 4, 5])

In [12]:
np.asanyarray(np.matrix(ls)) # will convert any item to an array

matrix([[1, 2, 3, 4, 5]])

In [13]:
# swallow copy - changes made in one insance will reflect inanother instance which is assigned or copied

In [14]:
a = arr

In [15]:
a

array([1, 2, 3, 4, 5])

In [16]:
arr[0] = 100 # due to swallow copy changes made in the main arr reflects in the assigned instance too


In [17]:
a

array([100,   2,   3,   4,   5])

In [18]:
b = np.copy(arr) # due to deep copy, changes made made in one instance will not reflect in another

In [19]:
b

array([100,   2,   3,   4,   5])

In [20]:
b[0] = 234
b

array([234,   2,   3,   4,   5])

In [21]:
arr

array([100,   2,   3,   4,   5])

In [22]:
# to generate metrices / arrays with n*n dimension, we can use the below function

np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [24]:
# to generate ranges

list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [25]:
iterable = (i*i for i in range(5))

In [26]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [27]:
np.fromstring('25 30 60', sep = ' ')

array([25., 30., 60.])

In [29]:
np.fromstring('25,30,60', sep = ',')

array([25., 30., 60.])

In [30]:
arr

array([100,   2,   3,   4,   5])

In [31]:
arr.ndim

1

In [32]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
arr1.ndim

2

In [35]:
arr.size # will return total number of elements

5

In [36]:
arr1.size

8

In [37]:
arr.shape

(5,)

In [38]:
arr1.shape

(2, 4)

In [39]:
arr.dtype

dtype('int64')

In [40]:
arr1.dtype

dtype('int64')