In [87]:
import numpy as np

In [88]:
# generating ranges

In [89]:
list(range(5))

[0, 1, 2, 3, 4]

In [90]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [91]:
np.arange(0.4, 10.4)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [92]:
np.arange(0.4, 10.4, 2)

array([0.4, 2.4, 4.4, 6.4, 8.4])

In [93]:
# generating data sets

In [94]:
np.linspace(1,5, 20) # generates data between 1 to 5 with 20 equally divided divisions

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [95]:
np.logspace(1, 5, 20) # same as above but with log base 10

array([1.00000000e+01, 1.62377674e+01, 2.63665090e+01, 4.28133240e+01,
       6.95192796e+01, 1.12883789e+02, 1.83298071e+02, 2.97635144e+02,
       4.83293024e+02, 7.84759970e+02, 1.27427499e+03, 2.06913808e+03,
       3.35981829e+03, 5.45559478e+03, 8.85866790e+03, 1.43844989e+04,
       2.33572147e+04, 3.79269019e+04, 6.15848211e+04, 1.00000000e+05])

In [96]:
np.zeros(5) # generate a dataset with zeroes

array([0., 0., 0., 0., 0.])

In [97]:
np.zeros((3,4)) # generate a dataset with 3 rows & 4 columns of zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
np.zeros((3,4,2)) # generates a dataset 

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [99]:
np.ones(5) # same as zeroes

array([1., 1., 1., 1., 1.])

In [100]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [101]:
arr = np.ones((3,4))

In [102]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [103]:
arr+3

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [104]:
np.empty((3,4)) # generates an empty array

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [105]:
np.eye(5) # creates an arry with equal rows & columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [106]:
arr1 = np.eye(5)

In [107]:
import pandas as pd

In [108]:
pd.DataFrame(arr1) # converting np arrays to DataFrames

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [109]:
np.random.rand(2,3)

array([[0.75543594, 0.41140816, 0.13757118],
       [0.16766869, 0.68159065, 0.34016667]])

In [110]:
np.random.randn(2,3) # generates normally distributed dataset

array([[ 1.10587964, -1.8934279 ,  0.03898257],
       [ 0.12789598,  0.2505106 , -0.28793498]])

In [111]:
np.random.randint(1,5, (3,4)) # generates random intreger dataset between the given range with gven rows and columns

array([[1, 1, 4, 3],
       [2, 3, 4, 3],
       [4, 2, 2, 4]])

In [112]:
arr2 = np.random.randint(1,5, (3,4))

In [113]:
arr2.size

12

In [114]:
arr2.shape

(3, 4)

In [115]:
arr2.reshape(6,2)

array([[2, 4],
       [1, 1],
       [1, 4],
       [1, 3],
       [3, 3],
       [2, 2]])

In [116]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [117]:
arr2.reshape(4,3)


array([[2, 4, 1],
       [1, 1, 4],
       [1, 3, 3],
       [3, 2, 2]])

In [118]:
arr2.reshape(4, -1)

array([[2, 4, 1],
       [1, 1, 4],
       [1, 3, 3],
       [3, 2, 2]])

In [119]:
arr2.reshape(2,2,3)

array([[[2, 4, 1],
        [1, 1, 4]],

       [[1, 3, 3],
        [3, 2, 2]]])

In [120]:
arr2.reshape(2,2,3,1,1,)

array([[[[[2]],

         [[4]],

         [[1]]],


        [[[1]],

         [[1]],

         [[4]]]],



       [[[[1]],

         [[3]],

         [[3]]],


        [[[3]],

         [[2]],

         [[2]]]]])

In [121]:
arr3 = np.random.randint(1,10, (5,6))

In [122]:
arr3

array([[7, 6, 8, 7, 1, 5],
       [7, 3, 7, 1, 1, 1],
       [1, 6, 6, 5, 5, 3],
       [5, 3, 2, 7, 6, 3],
       [5, 6, 8, 9, 2, 5]])

In [123]:
arr3 > 8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False]])

In [125]:
arr3[arr3 > 8 ] # extract the dataset with the given conditon

array([9])

In [127]:
arr3[0] # extract an dataset (subset)

array([7, 6, 8, 7, 1, 5])

In [128]:
arr[0, [0,1]]

array([1., 1.])

In [130]:
arr3[2:4, [2,3]] #extracting a subset from an array

array([[6, 5],
       [2, 7]])

In [131]:
arr4 = np.random.randint(1,3, (3,3))

arr5 = np.random.randint(1,3, (3,3))

In [132]:
arr4

array([[1, 1, 2],
       [2, 1, 1],
       [2, 2, 1]])

In [133]:
arr5

array([[2, 2, 1],
       [2, 1, 2],
       [1, 1, 1]])

In [136]:
arr4 + arr5  # we can perform multiple mathematical opearations on arrays

array([[3, 3, 3],
       [4, 2, 3],
       [3, 3, 2]])

In [139]:
arr4 @ arr5  # matrix mutiplication

array([[6, 5, 5],
       [7, 6, 5],
       [9, 7, 7]])

In [140]:
arr4 / arr5

array([[0.5, 0.5, 2. ],
       [1. , 1. , 0.5],
       [2. , 2. , 1. ]])

In [141]:
arr4 / 0

/tmp/ipykernel_102/3327478922.py:1: RuntimeWarning: divide by zero encountered in divide
  arr4 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [143]:
# numpy - broadcasting

In [144]:
arr6 = np.zeros((3,4))

In [145]:
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [146]:
arr6 + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [150]:
a = np.array([1,2,3,4])

In [153]:
a

array([1, 2, 3, 4])

In [154]:
arr6 + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [157]:
b = np.array([[3,4,5]])

In [159]:
b

array([[3, 4, 5]])

In [160]:
arr6 + b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [161]:
arr6 + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [162]:
b.T

array([[3],
       [4],
       [5]])

In [164]:
arr7 = arr6 + b.T

In [165]:
arr7

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [166]:
np.sqrt(arr7)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [167]:
np.log10(arr7)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [168]:
np.exp(arr7)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [169]:
np.min(arr7)

3.0

In [170]:
np.max(arr7)

5.0