In [1]:
import numpy as np

In [2]:
# Numpy - Sort, Search & Counting Functions

In [3]:
arr = np.random.randint(5, 25, (4, 4))

In [4]:
arr

array([[ 5, 20, 13, 24],
       [17, 17,  6, 22],
       [ 8, 21, 23,  7],
       [14, 14, 11,  9]])

In [5]:
np.sort(arr)

array([[ 5, 13, 20, 24],
       [ 6, 17, 17, 22],
       [ 7,  8, 21, 23],
       [ 9, 11, 14, 14]])

In [6]:
arr1 = np.array([4,5,2,8,56,12,5,9,5,3,1,6,63,1,4,3,4,6232,7,3,24,0,1,3,5])

In [7]:
np.sort(arr1)

array([   0,    1,    1,    1,    2,    3,    3,    3,    3,    4,    4,
          4,    5,    5,    5,    5,    6,    7,    8,    9,   12,   24,
         56,   63, 6232])

In [8]:
np.searchsorted(arr1, 6)

11

In [9]:
np.count_nonzero(arr1)

24

In [11]:
np.where( arr1 > 1 ) # indices of the elements which met condition

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 14, 15, 16, 17, 18,
        19, 20, 23, 24]),)

In [12]:
np.extract( arr1 > 2, arr1 )

array([   4,    5,    8,   56,   12,    5,    9,    5,    3,    6,   63,
          4,    3,    4, 6232,    7,    3,   24,    3,    5])

In [13]:
# Numpy - Bite Swapping.

In [14]:
arr1

array([   4,    5,    2,    8,   56,   12,    5,    9,    5,    3,    1,
          6,   63,    1,    4,    3,    4, 6232,    7,    3,   24,    0,
          1,    3,    5])

In [15]:
arr1.byteswap()

array([ 288230376151711744,  360287970189639680,  144115188075855872,
        576460752303423488, 4035225266123964416,  864691128455135232,
        360287970189639680,  648518346341351424,  360287970189639680,
        216172782113783808,   72057594037927936,  432345564227567616,
       4539628424389459968,   72057594037927936,  288230376151711744,
        216172782113783808,  288230376151711744, 6347823674778714112,
        504403158265495552,  216172782113783808, 1729382256910270464,
                         0,   72057594037927936,  216172782113783808,
        360287970189639680])

In [16]:
arr1.byteswap(True)

array([ 288230376151711744,  360287970189639680,  144115188075855872,
        576460752303423488, 4035225266123964416,  864691128455135232,
        360287970189639680,  648518346341351424,  360287970189639680,
        216172782113783808,   72057594037927936,  432345564227567616,
       4539628424389459968,   72057594037927936,  288230376151711744,
        216172782113783808,  288230376151711744, 6347823674778714112,
        504403158265495552,  216172782113783808, 1729382256910270464,
                         0,   72057594037927936,  216172782113783808,
        360287970189639680])

In [17]:
# Numpy - Copies & Views

In [20]:
arr1

array([ 288230376151711744,  360287970189639680,  144115188075855872,
        576460752303423488, 4035225266123964416,  864691128455135232,
        360287970189639680,  648518346341351424,  360287970189639680,
        216172782113783808,   72057594037927936,  432345564227567616,
       4539628424389459968,   72057594037927936,  288230376151711744,
        216172782113783808,  288230376151711744, 6347823674778714112,
        504403158265495552,  216172782113783808, 1729382256910270464,
                         0,   72057594037927936,  216172782113783808,
        360287970189639680])

In [21]:
a = np.copy(arr1) # creates a deep copy

In [24]:
b = arr1.view() # creates a swallow copy

In [25]:
b

array([ 288230376151711744,  360287970189639680,  144115188075855872,
        576460752303423488, 4035225266123964416,  864691128455135232,
        360287970189639680,  648518346341351424,  360287970189639680,
        216172782113783808,   72057594037927936,  432345564227567616,
       4539628424389459968,   72057594037927936,  288230376151711744,
        216172782113783808,  288230376151711744, 6347823674778714112,
        504403158265495552,  216172782113783808, 1729382256910270464,
                         0,   72057594037927936,  216172782113783808,
        360287970189639680])

In [26]:
b[0] = 234

In [27]:
b

array([                234,  360287970189639680,  144115188075855872,
        576460752303423488, 4035225266123964416,  864691128455135232,
        360287970189639680,  648518346341351424,  360287970189639680,
        216172782113783808,   72057594037927936,  432345564227567616,
       4539628424389459968,   72057594037927936,  288230376151711744,
        216172782113783808,  288230376151711744, 6347823674778714112,
        504403158265495552,  216172782113783808, 1729382256910270464,
                         0,   72057594037927936,  216172782113783808,
        360287970189639680])

In [28]:
arr1

array([                234,  360287970189639680,  144115188075855872,
        576460752303423488, 4035225266123964416,  864691128455135232,
        360287970189639680,  648518346341351424,  360287970189639680,
        216172782113783808,   72057594037927936,  432345564227567616,
       4539628424389459968,   72057594037927936,  288230376151711744,
        216172782113783808,  288230376151711744, 6347823674778714112,
        504403158265495552,  216172782113783808, 1729382256910270464,
                         0,   72057594037927936,  216172782113783808,
        360287970189639680])

In [29]:
# Numpy - Matrix libraby

In [30]:
import numpy.matlib as nm

In [32]:
nm.zeros(5) # creates a 2D matrix

matrix([[0., 0., 0., 0., 0.]])

In [33]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [35]:
# Numpy  - Linear Algebra

In [39]:
a = np.random.randint(1,10, (4, 4))

In [40]:
b = np.random.randint(1,10, (4, 4))

In [41]:
a

array([[5, 8, 3, 4],
       [2, 3, 9, 4],
       [7, 5, 2, 2],
       [5, 7, 3, 5]])

In [42]:
b

array([[8, 8, 3, 1],
       [8, 4, 2, 7],
       [4, 9, 3, 7],
       [5, 5, 4, 6]])

In [43]:
np.dot(a, b)

array([[136, 119,  56, 106],
       [ 96, 129,  55, 110],
       [114, 104,  45,  68],
       [133, 120,  58, 105]])

In [45]:
a@b

array([[136, 119,  56, 106],
       [ 96, 129,  55, 110],
       [114, 104,  45,  68],
       [133, 120,  58, 105]])